config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  # For details on DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  scope '(:locale)', constraints: { locale: /(cs-CZ|en-US|ja|pt)/ } do # rubocop:disable Metrics/BlockLength
    get '/radiation_index' => 'radiation_index#radiation_index'
    get '/ingest' => 'ingest#index'

    get '/airnote/:device_urn' => 'device_stories#show'

    root to: 'dashboards#show'
    devise_for :users
    devise_for :admins
    devise_scope :user do
      get '/logout' => 'devise/sessions#destroy', :as => :logout
    end

    resource :home, controller: :home, only: :show
    resource :dashboard, only: %i(show)
    resource :profile

    resource :cron, only: :create

    namespace :bgeigie_imports do
      resources :not_approved, only: :index
      resources :not_processed, only: :index
      resources :awaiting_response, only: :index
      resources :auto_approved, only: :index
      resources :not_submitted, only: :index
      resources :rejected_import, only: :index
    end

    resources :bgeigie_imports do
      resources :bgeigie_logs, only: :index
      member do
        patch :submit
        put :submit
        patch :reject
        patch :unreject
        patch :approve
        patch :fixdrive
        patch :process_button
        patch :send_email
        patch :contact_moderator
        get :kml
        get :kmz
        patch :resolve
      end
    end
    resources :devices do
      resources :measurements, only: :index
    end
    resources :measurement_imports do
      resources :measurements, only: :index
    end
    resources :measurements do
      collection do
        get :count
      end
    end
    resources :users do
      resources :measurements, only: :index
      get :me, on: :collection
    end
    resources :device_stories, only: %i(index show) do
      resources :device_story_comments
    end
  end

  match '/api/*path' => redirect('/%{path}.%{format}'), :format => true, via: %i(get post put delete)
  match '/api/*path' => redirect('/%{path}'), :format => false, via: %i(get post put delete)
  post '/api/measurements' => 'measurements#create'
  post '/api/measurements.(:format)' => 'measurements#create'

  # legacy fixes (maps.safecast.org now redirects to api.safecast.org, so people might be using the old maps.safecast.org/drive/add URI)
  match '/drive/add', to: redirect('/'), via: %i(get)
  match '/count', to: 'measurements#count', via: %i(get)

  resources :api_docs, only: [:index]

  match '/ingest.csv' => 'ingest#index', via: :get, defaults: { format: :csv }
end

app/views/notifications/contact_moderator.html.erb
<p>Click <%= link_to 'here', bgeigie_import_url(@import) %> to see import.</p>
<br>
<%= @body %>

app/views/notifications/import_approved.html.erb
<p>Your Safecast import has been approved.</p>
<p>Click <%= link_to("here", bgeigie_import_url(@import)) %> to view it.</p>

app/views/notifications/import_awaiting_approval.html.erb
<p>There is a Safecast import awaiting moderator approval.</p>

<p>Click <%= link_to "here", bgeigie_import_url(@import,
                                                :host => 'api.safecast.org',
                                                :protocol => 'https') %> to view it.</p>
<p>Import filename: <%= @import.filename %></p>
<p>Import type: <%= @import.type %></p>
<p>Status: <%= @import.status %></p>
<p>Measurements Count: <%= @import.measurements_count %></p>
<p>Created At: <%= @import.created_at %></p>
<p>Updated At: <%= @import.updated_at %></p>
<p>User Name: <%= @import.user.name %></p>
<p>User Email: <%= @import.user.email %></p>
<p>Name: <%= @import.name %></p>
<p>Description: <%= @import.description %></p>
<p>Lines Count: <%= @import.lines_count %></p>
<p>Credits: <%= @import.credits %></p>
<p>Height: <%= @import.height %></p>
<p>Orientation: <%= @import.orientation %></p>
<p>Cities: <%= @import.cities %></p>
<p>Subtype: <%= @import.subtype %></p>
<p>Comment: <%= @import.comment %></p>

app/views/notifications/import_awaiting_approval_digest.html.erb
<p>The following Safecast imports have been submitted in the last day.  They are awaiting moderator approval.</p>

<%- if @imports -%>
  <ul>
    <%- @imports.each do |bgeigie_import| -%>
      <li>
        <%= link_to File.basename(bgeigie_import.source.file.path),
          bgeigie_import_url(bgeigie_import,
                             :host => 'api.safecast.org',
                             :protocol => 'https') -%>
        (<%= pluralize(bgeigie_import.measurements_count, 'measurement') -%>)
        <%= t("uploaded_by", :name => link_to(bgeigie_import.user.name, bgeigie_import.user)).html_safe -%>
        <%= t("on_date", :date => bgeigie_import.created_at.to_formatted_s(:default)) %>
      </li>
    <%- end -%>
  </ul>
<%- end -%>

<p>Or click
<%= link_to "here", bgeigie_imports_url(:host => 'api.safecast.org',
                                        :protocol => 'https') %>
to see the list of imports.</p>

app/views/notifications/import_rejected.html.erb
<p>Your Safecast import has been rejected.</p>

<p>Click <%= link_to("here", bgeigie_import_url(@import)) %> to view it.</p>
<p>Comment: <%= @import.comment %></p>

app/views/notifications/send_email.html.erb
<p>Click <%= link_to 'here', bgeigie_import_url(@import) %> to see import.</p>
<br>
<%= @body %>